2025-03-18 16:22:23,474 [INFO] APIConnect.APIConnect: Loggers initiated with provided configuration.
2025-03-18 16:22:23,483 [INFO] constants.router: Router object is being created.
2025-03-18 16:22:23,483 [INFO] constants.router: URL constants loaded with provided configuration file.
2025-03-18 16:22:23,483 [INFO] APIConnect.http: Http object is being created.
2025-03-18 16:22:23,483 [INFO] APIConnect.login_helper: LoginHelper object is being created.
2025-03-18 16:22:23,483 [INFO] APIConnect.order_helper: OrderHelper object is being created.
2025-03-18 16:22:23,488 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): nc.nuvamawealth.com:443
2025-03-18 16:22:24,655 [DEBUG] urllib3.connectionpool: https://nc.nuvamawealth.com:443 "POST /edelmw-login/login/accounts/loginvendor/04FCaiaW37pOKA/ HTTP/1.1" 200 None
2025-03-18 16:22:24,664 [INFO] APIConnect.login_helper: User logged in successfully.
2025-03-18 16:22:24,664 [INFO] APIConnect.login_helper: Vendor session generated.
2025-03-18 16:22:24,731 [DEBUG] urllib3.connectionpool: https://nc.nuvamawealth.com:443 "POST /edelmw-login/login/accounts/logindata/ HTTP/1.1" 200 None
2025-03-18 16:22:24,733 [DEBUG] APIConnect.login_helper: Login details are pickled in file.
2025-03-18 16:22:24,733 [INFO] APIConnect.login_helper: Authorization done succesfully.
2025-03-18 16:22:24,766 [INFO] APIConnect.api_utils: Checking for new update.
2025-03-18 16:22:24,818 [INFO] feed.feed: Connection established with subscriber.
2025-03-18 16:22:24,899 [DEBUG] urllib3.connectionpool: https://nc.nuvamawealth.com:443 "POST /edelmw-content/content/adhoc/lib/version/ HTTP/1.1" 200 None
2025-03-18 16:22:24,899 [DEBUG] APIConnect.api_utils: Response received: {'appID': 'a5cbb543e3a7fb6bb063356377d6ad55', 'config': {'app': 1, 'bseExp': 1742256019006, 'exp': 1742256018995, 'info': 4}, 'data': {'type': 'libVsnResponseDao', 'msg': '', 'sts': True, 'vsn': '2.0.2'}, 'msgID': 'f09239a4-34c1-41c8-8e11-9fe0875e1c04', 'srvTm': 1742295145410}
2025-03-18 16:22:24,899 [ERROR] APIConnect.login_helper: Error occurred while downloading/ reading instruments: [Errno 2] No such file or directory: 'instruments.zip'
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\APIConnect\login_helper.py", line 119, in _Instruments
    with zipfile.ZipFile('instruments.zip', 'r') as zip_ref:
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'instruments.zip'
2025-03-18 16:22:24,972 [INFO] users: User 45937331 modified successfully.
2025-03-18 16:22:24,974 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:22:24] "POST /api/validate_user HTTP/1.1" 200 -
2025-03-18 16:22:32,244 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:22:32] "GET /api/users HTTP/1.1" 200 -
2025-03-18 16:22:46,661 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:22:46] "GET /api/all_users HTTP/1.1" 200 -
2025-03-18 16:24:05,407 [INFO] users: User 45937400 added successfully.
2025-03-18 16:24:05,413 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:24:05] "POST /api/add_user HTTP/1.1" 200 -
2025-03-18 16:24:08,707 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:24:08] "[31m[1mPOST /api/add_user HTTP/1.1[0m" 400 -
2025-03-18 16:24:38,239 [DEBUG] __main__: Modify_user()- {'active': False, 'apiKey': '04FCaiaW37pOKA', 'api_secret_password': '6LWnI8#Vl%nAsl*w', 'reqId': '393266cb0e251043', 'session_active': True, 'userid': '45937400', 'username': 'Irfan Patel 111'}
2025-03-18 16:24:38,306 [INFO] users: User 45937400 modified successfully.
2025-03-18 16:24:38,306 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:24:38] "POST /api/modify_user HTTP/1.1" 200 -
2025-03-18 16:24:47,083 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:24:47] "GET /api/users HTTP/1.1" 200 -
2025-03-18 16:24:55,323 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:24:55] "GET /api/all_users HTTP/1.1" 200 -
2025-03-18 16:25:37,263 [DEBUG] __main__: Modify_user()- {'active': True, 'apiKey': '04FCaiaW37pOKA', 'api_secret_password': '6LWnI8#Vl%nAsl*w', 'reqId': '393266cb0e251043', 'session_active': True, 'userid': '45937400', 'username': 'Irfan Patel 111'}
2025-03-18 16:25:37,366 [INFO] users: User 45937400 modified successfully.
2025-03-18 16:25:37,366 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:25:37] "POST /api/modify_user HTTP/1.1" 200 -
2025-03-18 16:25:40,386 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:25:40] "GET /api/users HTTP/1.1" 200 -
2025-03-18 16:26:01,536 [INFO] users: Deleting user 45937400 from DataFrame.
2025-03-18 16:26:01,538 [INFO] users: User 45937400 deleted. Saving changes to Excel.
2025-03-18 16:26:01,573 [INFO] users: User 45937400 deleted successfully.
2025-03-18 16:26:01,573 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:26:01] "POST /api/delete_user HTTP/1.1" 200 -
2025-03-18 16:26:03,573 [ERROR] __main__: Error in api_delete_user: User 45937400 not found.
2025-03-18 16:26:03,573 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:26:03] "[35m[1mPOST /api/delete_user HTTP/1.1[0m" 500 -
2025-03-18 16:26:09,000 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:26:09] "GET /api/users HTTP/1.1" 200 -
2025-03-18 16:26:15,390 [INFO] werkzeug: 127.0.0.1 - - [18/Mar/2025 16:26:15] "GET /api/all_users HTTP/1.1" 200 -
